### ISSUE TITLE
Add guide to set-up Cloud9

### ISSUE THREAD

**Issue by frahugo** [civilcode/playbook#63]
- [ ] Document under `guides/ops` the process of adding a new Cloud9 instance and provisionning it
- [ ] Add missing configuration/tools

Few things we had to do this week while using Cloud9:

- Remove ssh key and use `https` url for the github repo
- add credential cache in gitconfig: `- git config --global credential.helper 'cache --timeout=3600'`
- replace `nano` with `vim` in gitconfig
- install `hub` for git (had to install golang and bundler)
- add our standard git aliases

Things we didn't have time to do:

- install inotify-tools and figure out a way to run `mix format` on a .ex or .exs file saved
- install zsh?

**Comment by nicholasjhenry** [comment]
@bokay have these been implemented in https://github.com/civilcode/cloud9-bootstrap? If not, I'll move this to the new repo. Just let me know :-)

**Comment by bokay** [comment]
Everything has been taken into account here.
